name: axon
description: Dart server framework for building scalable and modular applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http_parser: ^4.0.0
  redis: ^4.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

